// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpWOmN0odtZLmyo64jxTJ-E8mCzziMCbo',
    appId: '1:935015268965:web:dc5604532f5c99da93bc8c',
    messagingSenderId: '935015268965',
    projectId: 'mad-gruppe-b-einkaufsliste',
    authDomain: 'mad-gruppe-b-einkaufsliste.firebaseapp.com',
    storageBucket: 'mad-gruppe-b-einkaufsliste.firebasestorage.app',
    measurementId: 'G-KY0NCSVKLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKjkbO7heYY74t4vOkZicyLxCAqukIkcw',
    appId: '1:935015268965:android:6b62a770a176d51a93bc8c',
    messagingSenderId: '935015268965',
    projectId: 'mad-gruppe-b-einkaufsliste',
    storageBucket: 'mad-gruppe-b-einkaufsliste.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL76C6-jsmMCo5u5D06Kr5bZPdYCtLg8E',
    appId: '1:935015268965:ios:4e1740ec058aaddd93bc8c',
    messagingSenderId: '935015268965',
    projectId: 'mad-gruppe-b-einkaufsliste',
    storageBucket: 'mad-gruppe-b-einkaufsliste.firebasestorage.app',
    iosBundleId: 'com.example.ffhsMadGruppeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL76C6-jsmMCo5u5D06Kr5bZPdYCtLg8E',
    appId: '1:935015268965:ios:4e1740ec058aaddd93bc8c',
    messagingSenderId: '935015268965',
    projectId: 'mad-gruppe-b-einkaufsliste',
    storageBucket: 'mad-gruppe-b-einkaufsliste.firebasestorage.app',
    iosBundleId: 'com.example.ffhsMadGruppeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpWOmN0odtZLmyo64jxTJ-E8mCzziMCbo',
    appId: '1:935015268965:web:16c661998e40834393bc8c',
    messagingSenderId: '935015268965',
    projectId: 'mad-gruppe-b-einkaufsliste',
    authDomain: 'mad-gruppe-b-einkaufsliste.firebaseapp.com',
    storageBucket: 'mad-gruppe-b-einkaufsliste.firebasestorage.app',
    measurementId: 'G-DJ7SY4RN2Z',
  );
}
